#cloud-config
package_update: true
package_upgrade: true
packages:
    - nginx
write_files:
    - owner: www-data:www-data
      path: /etc/nginx/sites-available/default
      content: |
          server {
            listen 80;
            location / {
              proxy_pass http://localhost:5000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection keep-alive;
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
            }
          }
runcmd:
    - service nginx restart
    - 'curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -' # Set up node repo to install node 16
    - 'sudo apt-get install -y nodejs'
    - 'sudo npm install pm2 -g' # Used for managing Express server
