name: Deploy to Azure VM

on:
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    deploy-files-to-vm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Copy files with rsync and start server
              run: |
                  ssh-keyscan -H ${{ secrets.HOST }} > known_hosts
                  echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d > ssh_key && chmod 400 ssh_key
                  echo SSH key file created with correct permissions!
                  rsync -avz -e "ssh -o GlobalKnownHostsFile=known_hosts -i ssh_key" ./src package.json ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/srv/
                  echo Files copied to host!
                  ssh -o GlobalKnownHostsFile=known_hosts -i ssh_key ${{ secrets.USERNAME }}@${{ secrets.HOST }} -t 'cd ./srv && pm2 stop express_web_server 2> /dev/null && npm install && npm start'
                  echo Application started!
              shell: bash
